version: '3.8'

services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'

  worker:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.payment_microservice
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - rabbitmq
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1

  server:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.app
    depends_on:
      - rabbitmq
    volumes:
      - ./:/app
    ports:
      - 5000:5000